name: CopySign
version: ${project.version}
main: us.ironcladnetwork.copySign.CopySign
api-version: '1.21'
authors: [ ClearPixels ]
description: Copy and paste sign text via NBT data
website: IroncladNetwork.us
depend: [ NBTAPI ]
softdepend: [ WorldGuard ]
permissions:
  # Base permissions
  copysign.use:
    description: Allows the player to use basic sign copy features
    default: op
  copysign.admin:
    description: Full administrative access to all CopySign features
    default: op
  copysign.reload:
    description: Allows the player to reload the plugin configuration
    default: op
    
  # Feature-specific permissions
  copysign.copycolor:
    description: Allows the player to copy sign color data
    default: op
  copysign.copyglow:
    description: Allows the player to copy sign glow state
    default: op
  copysign.copy.regular:
    description: Allows copying from regular signs
    default: op
  copysign.copy.hanging:
    description: Allows copying from hanging signs
    default: op
  copysign.paste.regular:
    description: Allows pasting to regular signs
    default: op
  copysign.paste.hanging:
    description: Allows pasting to hanging signs
    default: op
    
  # Library permissions
  copysign.library:
    description: General access to sign library features
    default: op
  copysign.library.save:
    description: Allows saving signs to personal library
    default: op
  copysign.library.load:
    description: Allows loading signs from personal library
    default: op
  copysign.library.delete:
    description: Allows deleting signs from personal library
    default: op
  copysign.library.view:
    description: Allows viewing personal library
    default: op
  copysign.library.unlimited:
    description: Bypasses library storage limits
    default: false
  copysign.library.limit.5:
    description: Allows storing up to 5 signs in library
    default: false
  copysign.library.limit.10:
    description: Allows storing up to 10 signs in library
    default: false
  copysign.library.limit.25:
    description: Allows storing up to 25 signs in library
    default: false
  copysign.library.limit.50:
    description: Allows storing up to 50 signs in library
    default: false
  copysign.library.limit.75:
    description: Allows storing up to 75 signs in library
    default: false
  copysign.library.limit.100:
    description: Allows storing up to 100 signs in library
    default: false
    
  # Template permissions
  copysign.templates:
    description: General access to server templates
    default: op
  copysign.templates.view:
    description: Allows viewing server templates
    default: op
  copysign.templates.use:
    description: Allows using server templates
    default: op
  copysign.templates.create:
    description: Allows creating server templates
    default: op
  copysign.templates.edit:
    description: Allows editing server templates
    default: op
  copysign.templates.delete:
    description: Allows deleting server templates
    default: op
    
  # Bypass permissions
  copysign.bypass.cooldowns:
    description: Bypasses command cooldowns
    default: false
  copysign.bypass.limits:
    description: Bypasses various plugin limits
    default: false
  copysign.bypass.worlds:
    description: Allows use in disabled worlds
    default: false
  copysign.bypass.worldguard:
    description: Bypasses WorldGuard region protection checks
    default: false
commands:
  copysign:
    description: Manage sign copying and library features
    usage: /copysign <on|off|clear|save|load|delete|library|reload|templates>
    aliases: [cs]
