name: CopySign
version: ${project.version}
main: us.ironcladnetwork.copySign.CopySign
api-version: '1.21'
authors: [ ClearPixels ]
description: Copy and paste sign text via NBT data
website: IroncladNetwork.us
depend: [ NBTAPI ]
permissions:
  copysign.use:
    description: Allows the player to use the sign copy feature.
    default: op
  copysign.copycolor:
    description: Allows the player to copy sign color data.
    default: op
  copysign.copyglow:
    description: Allows the player to copy sign glow state.
    default: op
  copysign.library:
    description: Allows the player to use sign library features.
    default: op
  copysign.reload:
    description: Allows the player to reload the plugin configuration.
    default: op
  copysign.templates:
    description: Allows the player to view and use server templates.
    default: op
  copysign.admin:
    description: Allows the player to create and manage server templates.
    default: op
commands:
  copysign:
    description: Manage sign copying and library features
    usage: /copysign <on|off|clear|save|load|delete|library|reload|templates>
    aliases: [cs]
