# CopySign Configuration
# Version: 2.0

# General Settings
general:
  # Default state for new players (whether sign copying is enabled by default)
  default-enabled: true
  
  # Check for plugin updates on startup
  check-for-updates: true
  
  # Enable debug messages in console
  debug: false

# Feature Toggles
features:
  # Enable/disable the entire sign copying feature
  sign-copy: true
  
  # Enable/disable the sign library feature
  sign-library: true
  
  # Enable/disable color copying (requires copysign.copycolor permission)
  copy-colors: true
  
  # Enable/disable glow state copying (requires copysign.copyglow permission)
  copy-glow: true
  
  # Enable/disable sign type checking (hanging vs regular signs)
  strict-sign-type: true
  
  # Enable/disable the clear command
  clear-command: true
  
  # Enable/disable server-wide templates
  server-templates: true

# Library Settings
library:
  # Maximum number of signs a player can save in their library
  # Set to -1 for unlimited
  max-saved-signs: 50
  
  # Allow players to overwrite existing saved signs
  allow-overwrite: false
  
  # GUI settings for the sign library
  gui:
    # Title of the library GUI
    title: "&b&lSign Library"
    
    # Number of rows in the GUI (1-6)
    rows: 6
    
    # Show sign preview in item lore
    show-preview: true

# Command Settings
commands:
  # Enable/disable specific subcommands
  enabled:
    on: true
    off: true
    clear: true
    save: true
    load: true
    delete: true
    library: true
    reload: true
  
  # Cooldowns for commands (in seconds)
  # Set to 0 to disable cooldown
  cooldowns:
    copy: 0
    paste: 0
    save: 2
    load: 1
    delete: 3
    clear: 1
    library: 1

# Sign Interaction Settings
sign-interaction:
  # Require sneaking (shift) to copy a sign
  require-sneak-to-copy: true
  
  # Require sneaking (shift) to paste a sign
  require-sneak-to-paste: false
  
  # Play sound effects
  sounds:
    enabled: true
    copy: "BLOCK_NOTE_BLOCK_PLING"
    paste: "BLOCK_NOTE_BLOCK_CHIME"
    save: "ENTITY_EXPERIENCE_ORB_PICKUP"
    error: "BLOCK_NOTE_BLOCK_BASS"

# Sign Type Restrictions
sign-types:
  # List of sign materials that can be copied
  # Remove or add materials to restrict/allow specific sign types
  allowed:
    - "OAK_SIGN"
    - "OAK_WALL_SIGN"
    - "OAK_HANGING_SIGN"
    - "OAK_WALL_HANGING_SIGN"
    - "SPRUCE_SIGN"
    - "SPRUCE_WALL_SIGN"
    - "SPRUCE_HANGING_SIGN"
    - "SPRUCE_WALL_HANGING_SIGN"
    - "BIRCH_SIGN"
    - "BIRCH_WALL_SIGN"
    - "BIRCH_HANGING_SIGN"
    - "BIRCH_WALL_HANGING_SIGN"
    - "JUNGLE_SIGN"
    - "JUNGLE_WALL_SIGN"
    - "JUNGLE_HANGING_SIGN"
    - "JUNGLE_WALL_HANGING_SIGN"
    - "ACACIA_SIGN"
    - "ACACIA_WALL_SIGN"
    - "ACACIA_HANGING_SIGN"
    - "ACACIA_WALL_HANGING_SIGN"
    - "DARK_OAK_SIGN"
    - "DARK_OAK_WALL_SIGN"
    - "DARK_OAK_HANGING_SIGN"
    - "DARK_OAK_WALL_HANGING_SIGN"
    - "MANGROVE_SIGN"
    - "MANGROVE_WALL_SIGN"
    - "MANGROVE_HANGING_SIGN"
    - "MANGROVE_WALL_HANGING_SIGN"
    - "CHERRY_SIGN"
    - "CHERRY_WALL_SIGN"
    - "CHERRY_HANGING_SIGN"
    - "CHERRY_WALL_HANGING_SIGN"
    - "BAMBOO_SIGN"
    - "BAMBOO_WALL_SIGN"
    - "BAMBOO_HANGING_SIGN"
    - "BAMBOO_WALL_HANGING_SIGN"
    - "CRIMSON_SIGN"
    - "CRIMSON_WALL_SIGN"
    - "CRIMSON_HANGING_SIGN"
    - "CRIMSON_WALL_HANGING_SIGN"
    - "WARPED_SIGN"
    - "WARPED_WALL_SIGN"
    - "WARPED_HANGING_SIGN"
    - "WARPED_WALL_HANGING_SIGN"

# Storage Settings
storage:
  # Auto-save interval for player data (in minutes)
  # Set to 0 to only save on server shutdown
  auto-save-interval: 5
  
  # Backup settings
  backup:
    enabled: true
    # Keep this many backups
    max-backups: 5
    # Backup on startup
    on-startup: true

# Protection Settings
protection:
  # Prevent players from copying signs in protected regions
  # Requires WorldGuard
  respect-worldguard: true
  
  # Prevent players from copying signs they don't own
  # Requires a protection plugin that tracks sign ownership
  respect-sign-ownership: false

# Performance Settings
performance:
  # Maximum number of signs that can be processed in a single operation
  max-batch-size: 100
  
  # Cache player toggle states in memory
  cache-toggle-states: true

# Metrics Settings
metrics:
  # Enable bStats metrics collection
  # This helps the developer understand how the plugin is being used
  # No personal data is collected - only anonymous usage statistics
  # You can view what data is collected at: https://bstats.org/plugin/bukkit/CopySign/26118
  enabled: true

# Don't modify this unless you know what you're doing
config-version: 1 